# Your inputs here
annotation:
  GRCh38: "data/Homo_sapiens.GRCh38.101.gtf.chr21.gz"
#  Ensembl: "data/Homo_sapiens.GRCh38.101.gtf.chr21.gz"
fastq_path: "data/test.fq"
reference_path: "data/Homo_sapiens.GRCh38.dna.chromosome.21.fa.gz"

# describe data here for talon
# see https://github.com/mortazavilab/TALON#run_talon, --f option
## reference genome build
reference_genome_name: "hg38"
sample_id: "SGNex_HepG2_directRNA_replicate1_run3"
sample_description: "hsa_tx"
