# paths to installed software
stringtie: "/home/genouest/cnrs_umr6290/fsassolas/stringtie-2.1.4.Linux_x86_64/stringtie"
gffcompare: "/home/genouest/cnrs_umr6290/fsassolas/gffcompare-0.11.6.Linux_x86_64/gffcompare"
paftools.js: "/home/genouest/cnrs_umr6290/fsassolas/paftools_test.js" # fix to avoid issues with the default paftools which doesnt work
bed12ToGtf: "~tderrien/bin/convert/bed12Togtf.sh"

# path to ref genome, annotation and fastq
## BEWARE : this part needs to be formatted as a dic {name:"path",name:"path",...}
annotation: {ens: "/groups/dog/data/canFam3/annotation/Ensembl99/Canis_familiaris.CanFam3.1.99.gtf", custom: "/groups/dog/data/canFam3/annotation/canfam3.2/canfam3_cons_annot_TritouPuppetMasterChief_23-03-2016_lncClasse_geneBiotype_withEnsCds_withSilicoCds_withGoodGeneSource.gtf"}
## simple paths
fastq_path: "/groups/dog/data/canFam3/NGS/Melanoma/RNA/MINION/Bear/20200227_1750_MN29715_FAL43795_4f1b5364/*/*fastq"
reference_path: "/home/genouest/cnrs_umr6290/tderrien/canFam3/sequence/softmasked/Canis_familiaris.CanFam3.1.72.dna_sm.toplevel.fa"

# describe data here for talon
# see https://github.com/mortazavilab/TALON#run_talon, --f option
## reference genome build
reference_build: "CanFam3"
## name of the cell line
cell_line: "Bearr"
data_type: "dog_tx"
